<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Manage_ds-coachmark-close</name>
   <tag></tag>
   <elementGuidId>986c688c-8a53-453e-b5f9-9da37f258fb6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[27]/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.ds-coachmark-close</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ds-coachmark-close</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;firefox firefox78 win32&quot;]/body[@class=&quot;navigator no-footer&quot;]/div[@class=&quot;ds-coachmark  uwa-overlay uwa-overlay-root&quot;]/span[@class=&quot;ds-coachmark-close&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[27]/span</value>
   </webElementXpaths>
</WebElementEntity>
